name: Build Electron App for All Platforms

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            script: build
          - os: macos-13
            script: build-mac
          - os: ubuntu-latest
            script: build-linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies on macOS (force x64)
        if: matrix.os == 'macos-13'
        env:
          npm_config_arch: x64
        run: |
          softwareupdate --install-rosetta --agree-to-license || true
          arch -x86_64 npm ci
        shell: bash

      - name: Install dependencies on Windows/Linux
        if: matrix.os != 'macos-13'
        run: npm ci

      - name: Build Electron App (${{ matrix.os }})
        run: |
          if [ "${{ matrix.os }}" == "macos-13" ]; then
            npm run build-mac -- --x64
          else
            npm run ${{ matrix.script }}
          fi
        shell: bash

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.os }}
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.exe
            dist/*.dmg
            dist/*.zip
