name: Build Electron App for All Platforms

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            script: build
          - os: macos-latest
            script: build-mac
          - os: ubuntu-latest
            script: build-linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Electron App (${{ matrix.os }})
        run: npm run ${{ matrix.script }}

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: electron-build-${{ matrix.os }}
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.exe
            dist/*.dmg
            dist/*.zip
